### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by luoxiangfan** [nuxt-community/imagemin-module#8]
![1](https://user-images.githubusercontent.com/58796647/80297583-fefccf00-87b6-11ea-9154-777cc132d145.PNG)
Error during installation

**Comment by ricardogobbosouza** [comment]
Hi @luoxiangfan 

Problem on [imagemin-gifsicle](https://github.com/imagemin/imagemin-gifsicle/issues/33)

**Comment by tex0l** [comment]
I cannot make `@nuxtjs/imagemin` work on Ubuntu 21.10 (installation issues), and imagemin's maintainer recommends switching to [Squoosh](https://github.com/GoogleChromeLabs/squoosh) (https://github.com/imagemin/imagemin/issues/385) 

Webpack has implemented the option to switch to squoosh (https://github.com/webpack-contrib/image-minimizer-webpack-plugin#options)

**Comment by ricardogobbosouza** [comment]
Hi @tex0l 
Unfortunately I can't update `image-minimizer-webpack-plugin` to its latest version because it uses `webpack5` and `nuxt2` does not support 5 =/
